"""add rolebase model

Revision ID: 039057a4c262
Revises: 06c73dbbe1c8
Create Date: 2026-02-04 12:19:40.308675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039057a4c262'
down_revision: Union[str, Sequence[str], None] = '06c73dbbe1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('rolename', sa.String(length=30), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_roles', sa.Boolean(), nullable=False),
    sa.Column('can_manage_events', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_access_page',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('home_page', sa.Boolean(), nullable=False),
    sa.Column('event_page', sa.Boolean(), nullable=False),
    sa.Column('user_page', sa.Boolean(), nullable=False),
    sa.Column('profile_page', sa.Boolean(), nullable=False),
    sa.Column('tiesheet_page', sa.Boolean(), nullable=False),
    sa.Column('group_page', sa.Boolean(), nullable=False),
    sa.Column('round_config_page', sa.Boolean(), nullable=False),
    sa.Column('qualifier_page', sa.Boolean(), nullable=False),
    sa.Column('participants_page', sa.Boolean(), nullable=False),
    sa.Column('column_config_page', sa.Boolean(), nullable=False),
    sa.Column('group_stage_standing_page', sa.Boolean(), nullable=False),
    sa.Column('todays_game_page', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('userrole',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('participants', 'is_winner')
    # op.drop_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', type_='unique')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # op.create_unique_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', ['id'], postgresql_nulls_not_distinct=False)
    op.add_column('participants', sa.Column('is_winner', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('userrole')
    op.drop_table('role_access_page')
    op.drop_table('roles')
    # ### end Alembic commands ###
