"""add winner field in tiesheetplayermatchscore

Revision ID: 06c73dbbe1c8
Revises: e167767d0f21
Create Date: 2026-02-02 15:42:07.071330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c73dbbe1c8'
down_revision: Union[str, Sequence[str], None] = 'e167767d0f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiesheet_player_match_score', sa.Column('winner', sa.Boolean(), nullable=False))
    op.alter_column('tiesheet_player_match_score', 'points',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # op.drop_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tiesheet_player_match_score', 'points',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('tiesheet_player_match_score', 'winner')
    # ### end Alembic commands ###
