"""added groupmembers table

Revision ID: 1937eae38b0f
Revises: 5694bc5dbff8
Create Date: 2026-01-14 14:02:36.902755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1937eae38b0f'
down_revision: Union[str, Sequence[str], None] = '5694bc5dbff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupmembers',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_groupmembers_user_id')
    )
    op.drop_constraint(op.f('groups_stage_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('stages_event_id_fkey'), 'stages', type_='foreignkey')
    op.create_foreign_key(None, 'stages', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages', type_='foreignkey')
    op.create_foreign_key(op.f('stages_event_id_fkey'), 'stages', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_stage_id_fkey'), 'groups', 'stages', ['stage_id'], ['id'])
    op.drop_table('groupmembers')
    # ### end Alembic commands ###
