"""remove progress note

Revision ID: 280799899f92
Revises: e28c8dd87566
Create Date: 2026-02-18 15:32:27.505671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280799899f92'
down_revision: Union[str, Sequence[str], None] = 'e28c8dd87566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'progress_note')
    op.drop_column('tiesheet_players', 'is_winner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiesheet_players', sa.Column('is_winner', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('progress_note', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
