"""add additional flag in role

Revision ID: 307531655991
Revises: 039057a4c262
Create Date: 2026-02-04 17:23:41.595878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307531655991'
down_revision: Union[str, Sequence[str], None] = '039057a4c262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('can_edit_users', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_create_users', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_delete_users', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_edit_roles', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_create_roles', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_delete_roles', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_edit_events', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_create_events', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('roles', sa.Column('can_delete_events', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('roles', 'can_manage_roles')
    op.drop_column('roles', 'can_manage_users')
    op.drop_column('roles', 'can_view')
    # op.drop_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(op.f('uq_tiesheet_players_id'), 'tiesheet_players', ['id'], postgresql_nulls_not_distinct=False)
    op.add_column('roles', sa.Column('can_view', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('can_manage_users', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('can_manage_roles', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('roles', 'can_delete_events')
    op.drop_column('roles', 'can_create_events')
    op.drop_column('roles', 'can_edit_events')
    op.drop_column('roles', 'can_delete_roles')
    op.drop_column('roles', 'can_create_roles')
    op.drop_column('roles', 'can_edit_roles')
    op.drop_column('roles', 'can_delete_users')
    op.drop_column('roles', 'can_create_users')
    op.drop_column('roles', 'can_edit_users')
    # ### end Alembic commands ###
