"""added is_winner in tiesheetplayer

Revision ID: 6184d481ac47
Revises: 280799899f92
Create Date: 2026-02-18 15:51:12.754749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6184d481ac47'
down_revision: Union[str, Sequence[str], None] = '280799899f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiesheet_players', sa.Column('is_winner', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiesheet_players', 'is_winner')
    # ### end Alembic commands ###
