"""remove round order

Revision ID: 61f2b0eda832
Revises: 63d45d2a66d2
Create Date: 2026-02-17 12:22:09.912920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f2b0eda832'
down_revision: Union[str, Sequence[str], None] = '63d45d2a66d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['rolename'])
    op.drop_column('roles', 'can_manage_events')
    op.drop_column('stages', 'round_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('round_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('can_manage_events', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
