"""make evnte_id nullable in userrole

Revision ID: 63d45d2a66d2
Revises: 87cd6f47c194
Create Date: 2026-02-09 10:48:00.828296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d45d2a66d2'
down_revision: Union[str, Sequence[str], None] = '87cd6f47c194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userrole', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userrole', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
