"""Added id in tiesheetplayer field

Revision ID: 6bf65f1bedcb
Revises: 724e21d998d4
Create Date: 2026-01-30 14:48:33.442918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf65f1bedcb'
down_revision: Union[str, Sequence[str], None] = '724e21d998d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiesheet_players', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiesheet_players', 'id')
    # ### end Alembic commands ###
