"""add event_id relation in group

Revision ID: 724e21d998d4
Revises: c72bfb836f9b
Create Date: 2026-01-28 15:56:29.056973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724e21d998d4'
down_revision: Union[str, Sequence[str], None] = 'c72bfb836f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('event_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'groups', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'event_id')
    # ### end Alembic commands ###
