"""add role page

Revision ID: 87cd6f47c194
Revises: 307531655991
Create Date: 2026-02-05 14:37:49.473352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87cd6f47c194'
down_revision: Union[str, Sequence[str], None] = '307531655991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_access_page', sa.Column('role_page', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_access_page', 'role_page')
    # ### end Alembic commands ###
