"""add is winner bool column in participants

Revision ID: 9cf881dc6691
Revises: 6e019287b515
Create Date: 2026-01-08 16:30:28.391278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf881dc6691'
down_revision: Union[str, Sequence[str], None] = '6e019287b515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('is_winner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'is_winner')
    # ### end Alembic commands ###
