"""change default value filed from columnval to standing column

Revision ID: af80b434ec98
Revises: c275554e708d
Create Date: 2026-01-16 16:41:28.192869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af80b434ec98'
down_revision: Union[str, Sequence[str], None] = 'c275554e708d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columnvalues', 'default_value')
    op.add_column('standingcolumns', sa.Column('default_value', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standingcolumns', 'default_value')
    op.add_column('columnvalues', sa.Column('default_value', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
