"""update the unique constraint in groupmember

Revision ID: c72bfb836f9b
Revises: af80b434ec98
Create Date: 2026-01-28 14:31:09.570173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72bfb836f9b'
down_revision: Union[str, Sequence[str], None] = 'af80b434ec98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groupmembers_user_id'), 'groupmembers', type_='unique')
    op.create_unique_constraint('uq_groupmembers_user_id_group_id', 'groupmembers', ['user_id', 'group_id'])
    op.add_column(
        'standingcolumns',
        sa.Column('to_show', sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standingcolumns', 'to_show')
    op.drop_constraint('uq_groupmembers_user_id_group_id', 'groupmembers', type_='unique')
    op.create_unique_constraint(op.f('uq_groupmembers_user_id'), 'groupmembers', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
