"""fixes columnvalues

Revision ID: c7c045c69cc5
Revises: 0b0172c87e22
Create Date: 2026-01-14 16:12:09.178984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c045c69cc5'
down_revision: Union[str, Sequence[str], None] = '0b0172c87e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('columnvalues_group_id_fkey'), 'columnvalues', type_='foreignkey')
    op.drop_constraint(op.f('columnvalues_stage_id_fkey'), 'columnvalues', type_='foreignkey')
    op.drop_column('columnvalues', 'stage_id')
    op.drop_column('columnvalues', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columnvalues', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('columnvalues', sa.Column('stage_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('columnvalues_stage_id_fkey'), 'columnvalues', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('columnvalues_group_id_fkey'), 'columnvalues', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
