"""update columnvalues

Revision ID: d4ac971fc070
Revises: c7c045c69cc5
Create Date: 2026-01-14 16:16:57.835021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ac971fc070'
down_revision: Union[str, Sequence[str], None] = 'c7c045c69cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columnvalues', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('columnvalues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('columnvalues', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columnvalues', 'updated_at')
    op.drop_column('columnvalues', 'created_at')
    op.drop_column('columnvalues', 'id')
    # ### end Alembic commands ###
