"""Added Player Score and Match of each tiesheet table

Revision ID: e167767d0f21
Revises: 6bf65f1bedcb
Create Date: 2026-01-30 14:48:59.596193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e167767d0f21'
down_revision: Union[str, Sequence[str], None] = '6bf65f1bedcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_tiesheet_players_id', 'tiesheet_players', ['id'])

    op.create_table('roundmatch',
    sa.Column('tiesheet_id', sa.UUID(), nullable=False),
    sa.Column('match_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tiesheet_id'], ['tiesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiesheet_player_match_score',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('tiesheetplayer_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['roundmatch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tiesheetplayer_id'], ['tiesheet_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'tiesheetplayer_id', name='uq_match_tiesheetplayer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiesheet_player_match_score')
    op.drop_table('roundmatch')
    # ### end Alembic commands ###
