"""added event role page

Revision ID: e28c8dd87566
Revises: 41006b67b36b
Create Date: 2026-02-18 10:21:49.809943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28c8dd87566'
down_revision: Union[str, Sequence[str], None] = '41006b67b36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_access_page', sa.Column('event_role_page', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_access_page', 'event_role_page')
    # ### end Alembic commands ###
